[package]
name = "strava-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
jiff = "0.2.4"
reqwest = "0.12"
tokio = { version = "1.44", features = ["full"] }

strava-sdk = { path = "../openapi-codegen" }
strava-client-rs = "0.2.5"
