/*
 * Strava API v3
 *
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};

/// struct for passing parameters to the method [`get_efforts_by_segment_id`]
#[derive(Clone, Debug)]
pub struct GetEffortsBySegmentIdParams {
    /// The identifier of the segment.
    pub segment_id: i32,
    /// ISO 8601 formatted date time.
    pub start_date_local: Option<String>,
    /// ISO 8601 formatted date time.
    pub end_date_local: Option<String>,
    /// Number of items per page. Defaults to 30.
    pub per_page: Option<i32>
}

/// struct for passing parameters to the method [`get_segment_effort_by_id`]
#[derive(Clone, Debug)]
pub struct GetSegmentEffortByIdParams {
    /// The identifier of the segment effort.
    pub id: i64
}


/// struct for typed errors of method [`get_efforts_by_segment_id`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetEffortsBySegmentIdError {
    DefaultResponse(models::Fault),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_segment_effort_by_id`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetSegmentEffortByIdError {
    DefaultResponse(models::Fault),
    UnknownValue(serde_json::Value),
}


/// Returns a set of the authenticated athlete's segment efforts for a given segment.  Requires subscription.
pub async fn get_efforts_by_segment_id(configuration: &configuration::Configuration, params: GetEffortsBySegmentIdParams) -> Result<Vec<models::DetailedSegmentEffort>, Error<GetEffortsBySegmentIdError>> {

    let uri_str = format!("{}/segment_efforts", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("segment_id", &params.segment_id.to_string())]);
    if let Some(ref param_value) = params.start_date_local {
        req_builder = req_builder.query(&[("start_date_local", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.end_date_local {
        req_builder = req_builder.query(&[("end_date_local", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.per_page {
        req_builder = req_builder.query(&[("per_page", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::DetailedSegmentEffort&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::DetailedSegmentEffort&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetEffortsBySegmentIdError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Returns a segment effort from an activity that is owned by the authenticated athlete. Requires subscription.
pub async fn get_segment_effort_by_id(configuration: &configuration::Configuration, params: GetSegmentEffortByIdParams) -> Result<models::DetailedSegmentEffort, Error<GetSegmentEffortByIdError>> {

    let uri_str = format!("{}/segment_efforts/{id}", configuration.base_path, id=params.id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::DetailedSegmentEffort`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::DetailedSegmentEffort`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetSegmentEffortByIdError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

